### ISSUE TITLE
Color mismatch with Themeify plugin

### ISSUE THREAD

**Issue by Naugrimohtar** [SanderRonde/Octoprint-Draggable-Files#1]
Hello! Great plugin! One item I noticed is a color mismatch of the resize handle versus the colored theme in Themeify . I am using [Themeify ](https://github.com/birkbjo/OctoPrint-Themeify)(1.2.2). I am not sure if its: 
-Themeify theme I am using doesn't define something it should, or 
-If there is some sort of tag you could use for coloring of the widget you added, or 
-If I need to do something on my end, or
-Other?

![ColorMismatch](https://user-images.githubusercontent.com/28710488/118808051-a808e280-b86e-11eb-976f-ae9bb671e3ed.PNG)

**Comment by SanderRonde** [comment]
Ah I completely forgot about Themeify. I think my solution (in commit a1e60ded6420287153966a1d07c8a3de1ade33b6) fixes the problem quite well. Due to some restrictions of the web platform I can't set the foreground color of the expand icon (the dashes). I can only set the background color. So my fix is to set the foreground color to either black or white, depending on whether the current theme is dark or not. The background color is set to the same background color as the scrollbar so it matches it nicely.

Here's an example since it's a bit of a long winded explanation:

![image](https://user-images.githubusercontent.com/5385012/118840996-2d6cb100-b8c8-11eb-9a43-7187477f79bb.png)
