### ISSUE TITLE
Scrolling and zooming no more possible after draging a file

### ISSUE THREAD

**Issue by chimcen** [SanderRonde/Octoprint-Draggable-Files#5]
Hi,

After draging a file on my iPhone the browser doesn’t response anymore til i reload the page - tested with safari and chrome in mobile and also desktop mode.

**Comment by SanderRonde** [comment]
Thanks for the bug report. I can definitely confirm the issue. It appears that it's impossible if not very hard to get dragging to work at all on mobile. I also get some issues with not being able to click the actual folders if I want to since the browser assumes I'm dragging.

Because of this, I've decided to just disable the dragging part of the plugin (which is most of it obviously) when the user is using a mobile browser.

Side note: personally I use a mobile app to connect to Octoprint on mobile. It makes the experience a lot better. I can recommend Octoremote on Android (not sure if it exists on iPhone as well), but there appear to be some for the iPhone as well.

I'll be closing the issue since it should be fixed in a recent commit.

**Comment by chimcen** [comment]
To remove this feature wasn‘t my intension - i‘m using it by a browser on mobiles for only 1% of all tasks…mostly by web or ios app.
My intension was just to give a feedback…

**Comment by SanderRonde** [comment]
It's not removed entirely. Only on mobile browsers. It seemed to not work at all on mobile (and even make navigating files higher). So going from not working at all (and freezing the website) to not being activated would be better right?

Do you think it would be better to re-activate it? What do you think a good solution would be?

**Comment by chimcen** [comment]
Yes, to disable it when browser identify as mobile client was a good idea.
It would also be great when you can handle the frame size (make it bigger/longer) of the file list with your plugin.

Found this on the web, but the idea seems to be dead… (didn‘t get a closer look til now)
https://community.octoprint.org/t/better-file-list-viewer/10607

**Comment by SanderRonde** [comment]
Conveniently the function of changing the frame size is already in the plugin. You can use the little drag-handle at the bottom right of the file list to grow or shrink the list.

Regarding the idea for a better file viewer. I definitely agree that that would be a good idea, however, implementing this as an Octoprint plugin would be very hard. It would be best if this was done as part of Octoprint itself. The reason for this is that the file viewer is already a part of Octoprint. So to improve the file viewer you have to take the already rendered file viewer and manipulate it to look like the example sketch in your link. An easier way would be to simply change the source code that renders it in the first place, which is in the main Octoprint source code.
